### ISSUE TITLE
[Request] interface cleanup?

### ISSUE THREAD

**Issue by frankzl** [Neihtq/typefast#6]
Instead of asking the user if they want to continue, just go on when the timer ends? Me as a terminal user, I'm mostly used to using KeyboardInterrupt to exit the command. And it feels a bit too much to type y/n after every sentence

Just a suggestion here, I ain't no hater :hand: :hand: 
Up for discussion

**Comment by vauhochzett** [comment]
I have to say, to me it's quite stressful that it immediately restarts... :D I like how on monkeytype it shows you your score, you can compare, and then decide to continue.

Say I want to take a screenshot of my score to brag – it does not work because I'm not so fast! 5 seconds are over before my screenshot tool boots... ;)
